{% set name = "typst" %}
{% set version = "0.15.0" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: https://github.com/{{ name }}/{{ name }}/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5044bd12138491c6e880df0e09056a9ae4607d937c73962d5806402ae6ee96a6

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('rust') }}
    - cargo-bundle-licenses
  host:
    - openssl  # [linux]
  run:
    - openssl  # [linux]

test:
  commands:
    - typst --version

about:
  home: https://github.com/typst/typst
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY_LICENSES.yaml
  summary: A new markup-based typesetting system that is powerful and easy to learn.

extra:
  recipe-maintainers:
    - AdrianFreundQC
    - freundTech
    - pavelzw
