schema_version: 1

context:
  version: 0.15.0

package:
  name: typst
  version: ${{ version }}

source:
  url: https://github.com/typst/typst/archive/refs/tags/v${{ version }}.tar.gz
  sha256: 5044bd12138491c6e880df0e09056a9ae4607d937c73962d5806402ae6ee96a6

build:
  number: 1
  script:
    env:
      CARGO_PROFILE_RELEASE_STRIP: symbols
      CARGO_PROFILE_RELEASE_LTO: fat
    content:
      - if: linux
        then:
          - export OPENSSL_DIR=$PREFIX
      - cd crates/typst-cli
      - if: unix
        then:
          - cargo auditable install --locked --no-track --bins --root ${{ PREFIX }} --path .
        else:
          - cargo auditable install --locked --no-track --bins --root %LIBRARY_PREFIX% --path .
      - cargo-bundle-licenses --format yaml --output ../../THIRDPARTY.yml
      - if: unix
        then:
          - mkdir -p $PREFIX/share/zsh/site-functions $PREFIX/share/bash-completion/completions $PREFIX/share/fish/vendor_completions.d
          - $PREFIX/bin/typst completions zsh > $PREFIX/share/zsh/site-functions/_typst
          - $PREFIX/bin/typst completions bash > $PREFIX/share/bash-completion/completions/typst
          - $PREFIX/bin/typst completions fish > $PREFIX/share/fish/vendor_completions.d/typst.fish
      - if: unix
        then:
          - mkdir -p $PREFIX/etc/conda/env_vars.d
          - 'echo {\"TYPST_PACKAGE_PATH\": \"$PREFIX/share/typst/packages\", \"TYPST_FONT_PATHS\": \"$PREFIX/fonts\"} > $PREFIX/etc/conda/env_vars.d/typst.json'
        else:
          - mkdir %PREFIX%\etc\conda\env_vars.d
          - 'set "FWD_PREFIX=%PREFIX:\=/%"'
          - 'echo {"TYPST_PACKAGE_PATH": "%FWD_PREFIX%/share/typst/packages", "TYPST_FONT_PATHS": "%FWD_PREFIX%/fonts"} > %PREFIX%\etc\conda\env_vars.d\typst.json'

requirements:
  build:
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('rust') }}
    - cargo-bundle-licenses
    - cargo-auditable
  host:
    - if: linux
      then: openssl

tests:
  - package_contents:
      bin:
        - typst
      files:
        - etc/conda/env_vars.d/typst.json
        - if: unix
          then:
            - share/bash-completion/completions/typst
            - share/fish/vendor_completions.d/typst.fish
            - share/zsh/site-functions/_typst
      strict: true
  - script:
      - typst --version
      - typst info
      - if: unix
        then:
          - typst info 2>&1 | grep TYPST_FONT_PATHS | grep $CONDA_PREFIX/fonts
          - typst info 2>&1 | grep TYPST_PACKAGE_PATH | grep $CONDA_PREFIX/share/typst/packages
        else:
          - 'set "FWD_CONDA_PREFIX=%CONDA_PREFIX:\=/%"'
          - 'typst info 2>&1 | findstr TYPST_FONT_PATHS | findstr "%FWD_CONDA_PREFIX%/fonts"'
          - 'typst info 2>&1 | findstr TYPST_PACKAGE_PATH | findstr "%FWD_CONDA_PREFIX%/share/typst/packages"'
  - requirements:
      run:
        - font-otf-fontawesome
    script:
      - typst fonts
      - if: unix
        then:
          - typst fonts | grep "Font Awesome"
        else:
          - typst fonts | findstr "Font Awesome"
about:
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
    - THIRDPARTY.yml
  summary: A markup-based typesetting system that is powerful and easy to learn.
  homepage: https://typst.app
  repository: https://github.com/typst/typst
  documentation: https://typst.app/docs

extra:
  recipe-maintainers:
    - AdrianFreundQC
    - freundTech
    - pavelzw
